# Generated by Django 4.2.2 on 2023-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RowOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(default='NA', upload_to='catalogue')),
                ('img2', models.ImageField(default='NA', upload_to='catalogue')),
                ('img3', models.ImageField(default='NA', upload_to='catalogue')),
                ('img4', models.ImageField(default='NA', upload_to='catalogue')),
                ('width', models.CharField(default='NA', max_length=50)),
                ('length', models.CharField(default='NA', max_length=50)),
            ],
            options={
                'verbose_name': 'Row One',
                'verbose_name_plural': 'Rows One',
            },
        ),
    ]
