# Generated by Django 4.2.2 on 2023-08-03 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowone',
            options={'verbose_name': 'Row one', 'verbose_name_plural': 'Row one'},
        ),
        migrations.AddField(
            model_name='rowone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rowone',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rowone',
            name='name',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
