# Generated by Django 4.2.2 on 2023-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_alter_rowone_options_rowone_created_rowone_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowone',
            name='id',
            field=models.CharField(default='NA', max_length=50, primary_key='True', serialize=False),
        ),
    ]
