# Generated by Django 4.2.2 on 2023-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0003_alter_rowone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowTwo',
            fields=[
                ('id', models.CharField(default='NA', max_length=50, primary_key='True', serialize=False)),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(default='NA', upload_to='catalogue')),
                ('img2', models.ImageField(default='NA', upload_to='catalogue')),
                ('img3', models.ImageField(default='NA', upload_to='catalogue')),
                ('img4', models.ImageField(default='NA', upload_to='catalogue')),
                ('width', models.CharField(default='NA', max_length=50)),
                ('length', models.CharField(default='NA', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Row two',
                'verbose_name_plural': 'Row two',
            },
        ),
    ]
