# Generated by Django 4.2.2 on 2023-09-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0004_rowtwo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RowOne',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='RowTwo',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
