# Generated by Django 4.2.2 on 2023-10-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0006_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
