# Generated by Django 4.2.2 on 2023-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0007_item_price_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
