# Generated by Django 4.2.2 on 2023-10-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0008_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='NA', max_length=250),
        ),
    ]
