# Generated by Django 4.2.2 on 2023-10-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0009_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue'),
        ),
    ]
