# Generated by Django 4.2.2 on 2023-10-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0010_alter_item_img1_alter_item_img2_alter_item_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, default='NA', null=True, upload_to='catalogue'),
        ),
    ]
