# Generated by Django 4.2.2 on 2023-10-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0013_alter_item_img3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue'),
        ),
    ]
