# Generated by Django 4.2.2 on 2023-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0014_alter_item_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sleeve',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
