# Generated by Django 4.2.2 on 2023-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0015_item_sleeve'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffPickups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img4', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('width', models.CharField(default='NA', help_text='Width in inches', max_length=50)),
                ('length', models.CharField(default='NA', help_text='Length in inches', max_length=50)),
                ('sleeve', models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50)),
                ('size', models.CharField(default='NA', max_length=50)),
                ('price', models.CharField(default='NA', help_text='Price in MXN', max_length=50)),
                ('description', models.CharField(default='NA', help_text='Information about the object', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'staffPickup',
                'verbose_name_plural': 'staffPickups',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='NA', help_text='Information about the object', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.CharField(default='NA', help_text='Length in inches', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default='NA', help_text='Price in MXN', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sleeve',
            field=models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(default='NA', help_text='Width in inches', max_length=50),
        ),
    ]
