# Generated by Django 4.2.2 on 2023-12-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0016_staffpickups_alter_item_description_alter_item_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img5',
            field=models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue'),
        ),
        migrations.AddField(
            model_name='item',
            name='img6',
            field=models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue'),
        ),
    ]
