# Generated by Django 4.2.2 on 2024-01-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0017_item_img5_item_img6'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpickups',
            name='img5',
            field=models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue'),
        ),
        migrations.AddField(
            model_name='staffpickups',
            name='img6',
            field=models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue'),
        ),
    ]
