# Generated by Django 4.2.2 on 2024-02-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0018_staffpickups_img5_staffpickups_img6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewerly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img4', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img5', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img6', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('width', models.CharField(default='NA', help_text='Width in inches', max_length=50)),
                ('length', models.CharField(default='NA', help_text='Length in inches', max_length=50)),
                ('sleeve', models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50)),
                ('size', models.CharField(default='NA', max_length=50)),
                ('price', models.CharField(default='NA', help_text='Price in MXN', max_length=50)),
                ('description', models.CharField(default='NA', help_text='Information about the object', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
