# Generated by Django 4.2.2 on 2024-02-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0019_jewerly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewerly',
            options={'verbose_name': 'Jewerly', 'verbose_name_plural': 'Jewerly'},
        ),
    ]
