# Generated by Django 4.2.2 on 2024-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0021_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('Jacket', 'Jacket'), ('Sweatshirt', 'Sweatshirt')], default='All', max_length=50),
        ),
    ]
