# Generated by Django 4.2.2 on 2025-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0024_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tees', 'Tees'), ('Jacket', 'Jacket'), ('Sweatshirt', 'Sweatshirt')], default='Tees', max_length=50),
        ),
    ]
