# Generated by Django 4.2.2 on 2025-06-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0025_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Check this if the item should appear in the curated 'Just In' section."),
        ),
    ]
