# Generated by Django 4.2.2 on 2025-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0026_item_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False, help_text='Check this if the item has been sold'),
        ),
    ]
