# Generated by Django 4.2.2 on 2025-06-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0027_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='is_sold',
        ),
    ]
