# Generated by Django 4.2.2 on 2025-06-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0028_rename_status_item_is_sold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staffPickups',
        ),
    ]
