# Generated by Django 4.2.2 on 2025-06-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0029_delete_staffpickups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tee', 'Tee'), ('Jacket', 'Jacket'), ('Sweatshirt', 'Sweatshirt'), ('StaffPick', 'StaffPick')], default='Tees', max_length=50),
        ),
    ]
