# Generated by Django 4.2.2 on 2025-06-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0030_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='staff_pick',
            field=models.BooleanField(default=False, help_text='Check this if the item is a staff pick'),
        ),
    ]
