# Generated by Django 4.2.2 on 2025-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0031_item_staff_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tee', 'Tee'), ('Jacket', 'Jacket'), ('Sweatshirt', 'Sweatshirt')], default='Tee', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(blank=True, help_text='Front', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, help_text='Back', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, help_text='Zoom-in 1', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.ImageField(blank=True, help_text='Zoom-in 2', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img5',
            field=models.ImageField(blank=True, help_text='Zoom-in 3', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img6',
            field=models.ImageField(blank=True, help_text='Zoom-in 4', null=True, upload_to='catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Check if item appears in the curated 'Just In' section."),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Check if this item has been sold'),
        ),
        migrations.AlterField(
            model_name='item',
            name='staff_pick',
            field=models.BooleanField(default=False, help_text='Check if this item is a staff pick.'),
        ),
    ]
