# Generated by Django 4.2.2 on 2025-06-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0032_alter_item_category_alter_item_img1_alter_item_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='NA', max_length=50),
        ),
    ]
