# Generated by Django 4.2.2 on 2025-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0033_alter_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tees', 'Tees'), ('Jacket', 'Jacket'), ('Sweatshirt', 'Sweatshirt')], default='Tee', max_length=50),
        ),
    ]
