# Generated by Django 4.2.2 on 2025-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0034_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tees', 'Tees'), ('Jackets', 'Jackets'), ('Sweatshirts', 'Sweatshirts')], default='Tee', max_length=50),
        ),
    ]
