# Generated by Django 4.2.2 on 2025-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0036_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_vintage',
            field=models.BooleanField(default=False, help_text='Check if the item should go to archive or be removed.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(blank=True, help_text='Catalogue image', null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, help_text='Front part', null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, help_text='Back part', null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.ImageField(blank=True, help_text='Zoom-in 1', null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img5',
            field=models.ImageField(blank=True, help_text='Zoom-in 2', null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img6',
            field=models.ImageField(blank=True, help_text='Zoom-in 3', null=True, upload_to='catalogue/original'),
        ),
    ]
