# Generated by Django 4.2.2 on 2025-06-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0037_item_is_vintage_alter_item_img1_alter_item_img2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_vintage',
            new_name='is_archive',
        ),
    ]
