# Generated by Django 4.2.2 on 2025-07-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0038_rename_is_vintage_item_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img7',
            field=models.ImageField(blank=True, help_text='Zoom-in 4', null=True, upload_to='catalogue/original'),
        ),
    ]
