# Generated by Django 4.2.2 on 2025-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0039_item_img7'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shopify_variant_id',
            field=models.CharField(blank=True, help_text='Shopify Variant ID used for direct checkout', max_length=50, null=True),
        ),
    ]
