# Generated by Django 4.2.2 on 2025-08-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0040_item_shopify_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shopify_handle',
            field=models.CharField(blank=True, help_text='Used to match products between Shopify and Django', max_length=100, null=True),
        ),
    ]
