# Generated by Django 4.2.2 on 2025-08-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0041_item_shopify_handle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='shopify_handle',
            field=models.CharField(blank=True, help_text='Used to match products between Shopify and Django', max_length=100, null=True, unique=True),
        ),
    ]
