# Generated by Django 4.2.2 on 2025-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0044_alter_item_shopify_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in MXN', max_digits=10, null=True),
        ),
    ]
