# Generated by Django 4.2.2 on 2025-09-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0045_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated (front-part)', null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated (zoom)', null=True, upload_to='catalogue/original'),
        ),
    ]
