# Generated by Django 4.2.2 on 2025-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0046_alter_item_img2_alter_item_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, help_text='Back', null=True, upload_to='catalogue/original'),
        ),
    ]
