# Generated by Django 4.2.2 on 2026-01-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0050_alter_item_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(blank=True, help_text='Catalogue image', max_length=500, null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated (front-part)', max_length=500, null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(blank=True, help_text='Back', max_length=500, null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.ImageField(blank=True, help_text='Zoom-in 1', max_length=500, null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img5',
            field=models.ImageField(blank=True, help_text='Zoom-in 2', max_length=500, null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img6',
            field=models.ImageField(blank=True, help_text='Zoom-in 3', max_length=500, null=True, upload_to='catalogue/original'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img7',
            field=models.ImageField(blank=True, help_text='Zoom-in 4', max_length=500, null=True, upload_to='catalogue/original'),
        ),
    ]
