# Generated by Django 4.2.2 on 2026-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0051_alter_item_img1_alter_item_img2_alter_item_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img1_h',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='img1_w',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
