# Generated by Django 4.2.2 on 2026-06-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0052_item_img1_h_item_img1_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewelry_type', models.CharField(choices=[('Necklace', 'Necklace')], default='Necklace', max_length=50)),
                ('staff_pick', models.BooleanField(default=False, help_text='Check if this jewelry item is a staff pick.')),
                ('is_featured', models.BooleanField(default=False, help_text="Check if item appears in the curated 'Just In' section.")),
                ('is_sold', models.BooleanField(default=False, help_text='Check if this item has been sold.')),
                ('is_archive', models.BooleanField(default=False, help_text='Check if the item should go to archive or be removed.')),
                ('sold_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.CharField(default='NA', help_text='Example: silver, stainless steel, brass', max_length=100)),
                ('chain_length', models.CharField(default='NA', help_text='Chain length, e.g. 45 cm', max_length=50)),
                ('pendant_size', models.CharField(default='NA', help_text='Pendant size, if applicable', max_length=50)),
                ('condition', models.CharField(default='Vintage / pre-owned', help_text='Condition of the piece', max_length=100)),
                ('img1_w', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img1_h', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img7', models.ImageField(blank=True, help_text='Zoom-in 4', max_length=500, null=True, upload_to='jewelry/original')),
                ('shopify_variant_id', models.CharField(blank=True, help_text='Shopify Variant ID used for direct checkout', max_length=50, null=True)),
                ('shopify_handle', models.CharField(blank=True, help_text='Used to match products between Shopify and Django', max_length=100, null=True, unique=True)),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img4', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img5', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img6', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('width', models.CharField(default='NA', help_text='Width in inches', max_length=50)),
                ('length', models.CharField(default='NA', help_text='Length in inches', max_length=50)),
                ('sleeve', models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50)),
                ('size', models.CharField(default='NA', max_length=50)),
                ('price', models.CharField(default='NA', help_text='Price in MXN', max_length=50)),
                ('description', models.CharField(default='NA', help_text='Information about the object', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jewerly',
                'verbose_name_plural': 'Jewerly',
            },
        ),
        migrations.DeleteModel(
            name='Jewerly',
        ),
    ]
