# Generated by Django 4.2.2 on 2026-07-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0053_jewelry_delete_jewerly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name': 'Jewelry', 'verbose_name_plural': 'Jewelry'},
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.CharField(default='NA', help_text='Length in cm', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sleeve',
            field=models.CharField(default='NA', help_text='Sleeve length in cm', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(default='NA', help_text='Width in cm', max_length=50),
        ),
    ]
