# Generated by Django 4.2.2 on 2026-07-08 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=20, unique=True)),
                ('date_bought', models.DateField()),
                ('source', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tshirt', 'T-shirt'), ('sweatshirt', 'Sweatshirt'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('pants', 'Pants'), ('jewelry', 'Jewelry'), ('other', 'Other')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=40)),
                ('era', models.CharField(blank=True, max_length=60)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listed_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('measurements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('published', 'Published'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('archive', 'Archive')], default='draft', max_length=20)),
                ('is_visible_on_site', models.BooleanField(default=False)),
                ('staff_pick', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments', to='Inventory.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=30, unique=True)),
                ('sale_date', models.DateField()),
                ('channel', models.CharField(choices=[('website', 'Website'), ('popup', 'Pop-up'), ('instagram', 'Instagram'), ('physical', 'Physical'), ('other', 'Other')], max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Inventory.garment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Inventory.sale')),
            ],
        ),
    ]
