# Generated by Django 4.2.2 on 2024-08-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img4', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img5', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img6', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('width', models.CharField(default='NA', help_text='Width in inches', max_length=50)),
                ('length', models.CharField(default='NA', help_text='Length in inches', max_length=50)),
                ('sleeve', models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50)),
                ('size', models.CharField(default='NA', max_length=50)),
                ('price', models.CharField(default='NA', help_text='Price in MXN', max_length=50)),
                ('description', models.CharField(default='NA', help_text='Information about the object', max_length=250)),
                ('category', models.CharField(choices=[('Tshirt', 'Tshirt'), ('Jacket', 'Jacket'), ('Sweatshirt', 'Sweatshirt')], default='Tshirt', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Jewerly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img4', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img5', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img6', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('width', models.CharField(default='NA', help_text='Width in inches', max_length=50)),
                ('length', models.CharField(default='NA', help_text='Length in inches', max_length=50)),
                ('sleeve', models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50)),
                ('size', models.CharField(default='NA', max_length=50)),
                ('price', models.CharField(default='NA', help_text='Price in MXN', max_length=50)),
                ('description', models.CharField(default='NA', help_text='Information about the object', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jewerly',
                'verbose_name_plural': 'Jewerly',
            },
        ),
        migrations.CreateModel(
            name='staffPickups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('img1', models.ImageField(blank=True, help_text='Front part of garment', null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, help_text='Back part of garment', null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img4', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img5', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('img6', models.ImageField(blank=True, help_text='Zoom-in details of garment', null=True, upload_to='catalogue')),
                ('width', models.CharField(default='NA', help_text='Width in inches', max_length=50)),
                ('length', models.CharField(default='NA', help_text='Length in inches', max_length=50)),
                ('sleeve', models.CharField(default='NA', help_text='Sleeve length in inches', max_length=50)),
                ('size', models.CharField(default='NA', max_length=50)),
                ('price', models.CharField(default='NA', help_text='Price in MXN', max_length=50)),
                ('description', models.CharField(default='NA', help_text='Information about the object', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'staffPickup',
                'verbose_name_plural': 'staffPickups',
            },
        ),
    ]
