# Generated by Django 4.2.2 on 2024-08-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Jewerly',
        ),
        migrations.DeleteModel(
            name='staffPickups',
        ),
    ]
