# Generated by Django 4.2.2 on 2024-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0002_delete_item_delete_jewerly_delete_staffpickups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
