# Generated by Django 4.2.2 on 2024-08-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
