# Generated by Django 4.2.2 on 2024-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_alter_image_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop All',
                'verbose_name_plural': 'Shop All',
            },
        ),
        migrations.CreateModel(
            name='Sweatshirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sweatshirt',
                'verbose_name_plural': 'Sweatshirts',
            },
        ),
        migrations.CreateModel(
            name='Tshirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tshirt',
                'verbose_name_plural': 'Tshirts',
            },
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Outerwear',
        ),
        migrations.AlterModelOptions(
            name='outerwear',
            options={'verbose_name': 'Outerwear', 'verbose_name_plural': 'Outerwear'},
        ),
    ]
