# Generated by Django 4.2.2 on 2025-04-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tshirts',
            new_name='Tees',
        ),
        migrations.AlterModelOptions(
            name='tees',
            options={'verbose_name': 'Tees', 'verbose_name_plural': 'Tees'},
        ),
    ]
