# Generated by Django 4.2.2 on 2025-06-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_newitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewItem',
        ),
    ]
