# Generated by Django 4.2.2 on 2025-06-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_delete_newitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tees',
            new_name='StaffPicks',
        ),
        migrations.AlterModelOptions(
            name='staffpicks',
            options={'verbose_name': 'StaffPick', 'verbose_name_plural': 'StaffPicks'},
        ),
    ]
