# Generated by Django 4.2.2 on 2025-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_rename_tees_staffpicks_alter_staffpicks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('menu', 'Menu'), ('shop_all', 'Shop All'), ('staff_picks', 'Staff Picks'), ('sweatshirts', 'Sweatshirts'), ('outerwear', 'Outerwear')], max_length=20)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='catalogue')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
            },
        ),
    ]
