# Generated by Django 4.2.2 on 2025-06-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_homepagesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Outerwear',
        ),
        migrations.DeleteModel(
            name='ShopAll',
        ),
        migrations.DeleteModel(
            name='StaffPicks',
        ),
        migrations.DeleteModel(
            name='Sweatshirts',
        ),
    ]
