# Generated by Django 4.2.2 on 2025-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_delete_menu_delete_outerwear_delete_shopall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='menu/original'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='menu/original'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='menu/original'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('shop_all', 'Shop All'), ('staff_picks', 'Staff Picks'), ('sweatshirts', 'Sweatshirts'), ('outerwear', 'Outerwear'), ('archive', 'Archive')], max_length=20),
        ),
    ]
