# Generated by Django 4.2.2 on 2025-08-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0013_alter_homepagesection_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('about', 'About'), ('shipping', 'Shipping & Returns'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='info/')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
