# Generated by Django 4.2.2 on 2025-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0014_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesection',
            options={},
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('shop_all', 'Shop All'), ('staff_picks', 'Staff Picks'), ('tees', 'Tees'), ('sweatshirts', 'Sweatshirts'), ('outerwear', 'Outerwear'), ('archive', 'Archive')], max_length=20),
        ),
    ]
