# Generated by Django 4.2.2 on 2025-09-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0016_alter_homepagesection_section_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesection',
            options={'verbose_name': 'Homepage Section', 'verbose_name_plural': 'Homepage Sections'},
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('shop_all', 'Shop All'), ('staff_picks', 'Staff Picks'), ('tees', 'Tees'), ('sweatshirts', 'Sweatshirts'), ('outerwear', 'Outerwear'), ('archive', 'Archive')], max_length=20),
        ),
    ]
