# Generated by Django 4.2.2 on 2026-06-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0017_alter_homepagesection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('shop_all', 'Shop All'), ('staff_picks', 'Staff Picks'), ('tees', 'Tees'), ('sweatshirts', 'Sweatshirts'), ('outerwear', 'Outerwear'), ('archive', 'Archive'), ('jewelry', 'Jewelry')], max_length=20),
        ),
    ]
